apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-shib # will be used in shiboleth volumeMounts
  labels:
      shared-shib: shib
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: "/data/shared-shibboleth-idp"