kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "shared-shib.fullname" . }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  volumeName: shared-shib 
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  selector:
    matchLabels:
      shared-shib: shib
  