apiVersion: v1
kind: Service
metadata:
  name: {{ template "gluu.fullname" . }}
  labels:
{{ include "gluu.labels" . | indent 4 }}
spec:
  # type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ template "gluu.fullname" . }}
  selector:
{{ include "gluu.labels" . | indent 4 }}
