apiVersion: v1
kind: ConfigMap
metadata: 
  name: config-cm
  namespace: default
data:
  ADMIN_PW: "P@ssw0rd"
  EMAIL: "support@gluu.com"
  ORG_NAME: "Gluu"
  COUNTRY_CODE: US
  STATE: TE
  CITY: SLC
  LDAP_TYPE: opendj
  GLUU_CONFIG_ADAPTER: kubernetes
  GLUU_SECRET_ADAPTER: kubernetes

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gen-json-file
  namespace: default
data:
  generate.json: |-
    {
      "hostname": "$DOMAIN",
      "country_code": "$COUNTRY_CODE",
      "state": "$STATE",
      "city": "$CITY",
      "admin_pw": "$ADMIN_PW",
      "email": "$EMAIL",
      "org_name": "$ORG_NAME"
    }

---


kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-volume-claim
spec:
  storageClassName: ""
  volumeName: config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
  selector:
    matchLabels:
      config-init: config

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
  labels:
      config-init: config
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/config/db"

---

apiVersion: batch/v1
kind: Job
metadata:
  name: config-init
spec:
  parallelism: 1
  template:
    metadata:
      name: job
      labels:
        app: load
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-volume-claim
        - name: mount-gen-file
          configMap:
            name: gen-json-file
      containers:
      - name: load
        image: gluufederation/config-init:4.0.0_dev
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sh", -c , "printenv" ]
        volumeMounts:
          - mountPath: /opt/config-init/db/
            name: config
          - mountPath: /opt/config-init/db/generate.json
            name: mount-gen-file
            subPath: generate.json
        envFrom:
        - configMapRef:
            name: config-cm
        args: [ "load" ]
      restartPolicy: Never
