dependencies:
  - name: config
    condition: config.enabled
    version: 1.1.0
  - name: ldap
    condition: ldap.enabled
    version: 1.1.0
  - name: oxauth
    condition: oxauth.enabled
    version: 1.1.0
  - name: shared-shib
    condition: shared-shib.enabled
    version: 1.1.0
  - name: oxtrust
    condition: oxtrust.enabled
    version: 1.1.0
  - name: oxpassport
    condition: oxpassport.enabled
    version: 1.1.0
