# Declare variables to be passed into your templates.

# values for config-init sub-chart
config:
  orgName: k8s
  # email address of the administrator usually. Used for certificate creation
  email: k8s@email.com
  # adminPass is administrator password for oxTrust and LDAP
  adminPass: password
  # domain name where the Gluu Server resides
  domain: localhost
  # organisation location details
  countryCode: US
  state: UT
  city: SLC
  # ldapType only OpenDJ is supported
  ldapType: opendj
  
global:
  namespace: default
  configAdapterName: kubernetes
  configSecretAdapter: kubernetes
  gluuConfigK8sNamespace: default
  gluuConfigK8sConfigmap: gluu
  gluuConfigK8sUseKubeConfig: false
  gluuSecretK8sNamespace: default
  gluuSecretK8sConfigmap: gluu
  gluuSecretK8sUseKubeConfig: false
  gluuSecretAdapter: kubernetes




