# Declare variables to be passed into your templates.

# Required environment variables for generating Gluu server initial config
# values for config-init sub-chart
config:
  orgName: gluu
  # email address of the administrator usually. Used for certificate creation
  email: support@gluu.com
  # adminPass is administrator password for oxTrust and LDAP
  adminPass: password
  # domain name where the Gluu Server resides
  domain: localhost
  # organisation location details
  countryCode: US
  state: UT
  city: SLC
  # ldapType only OpenDJ is supported
  ldapType: opendj
  configAdapterName: kubernetes
  configSecretAdapter: kubernetes
  
  # StorageClass values
  # values used to define the StorageClass template
  encrypted: true
  reclaimPolicy: Retain
  pool: default
  description: gluu-config-init-volume
  fsType: ext4
  provisioner: k8s.io/minikube-hostpath
  awsZones: us-west-2a
  gcePdStorageType: pd-standard
  azureStorageAccountType: Standard_LRS
  azureStorageKind: Shared

oxauth:
  enabled: true
  dynamicStorage: true

ldap:
  enabled: true

shared-shib:
  enabled: true
  dynamicStorage: true

oxtrust:
  enabled: true
  dynamicStorage: true

nginx:
  enabled: true 

oxpassport:
  enabled: false 

key-rotation:
  enabled: true

cr-rotate:
  enabled: true 

global:
  namespace: default
  serviceName: opendj
  nginxIp: 192.168.99.100
  oxAuthServiceName: oxauth
  oxTrustSeriveName: oxtrust
  domain: demoexample.gluu.org
  gluuLdapUrl: opendj:1636
  gluuMaxRamFraction: 1
  configAdapterName: kubernetes
  configSecretAdapter: kubernetes
  gluuConfigK8sNamespace: default
  gluuConfigK8sConfigmap: gluu
  gluuConfigK8sUseKubeConfig: false
  gluuSecretK8sNamespace: default
  gluuSecretK8sConfigmap: gluu
  gluuSecretK8sUseKubeConfig: false
  gluuSecretAdapter: kubernetes
  provisioner: k8s.io/minikube-hostpath
  