# Required environment variables for generating Gluu server initial config
# values for config-init sub-chart
config:
  orgName: gluu
  # email address of the administrator usually. Used for certificate creation
  email: support@gluu.com
  # adminPass is administrator password for oxTrust and LDAP
  adminPass: P@ssw0rd
  # domain name where the Gluu Server resides
  domain: localhost
  # organisation location details
  countryCode: US
  state: UT
  city: SLC
  # ldapType only OpenDJ is supported
  ldapType: opendj
  
  # StorageClass values
  # values used to define the StorageClass template
  encrypted: true
  reclaimPolicy: Retain
  pool: default
  description: gluu-config-init-volume
  fsType: ext4
  provisioner: k8s.io/minikube-hostpath
  awsZones: us-west-2a
  gcePdStorageType: pd-standard
  azureStorageAccountType: Standard_LRS
  azureStorageKind: Shared
  extraHosts: []

oxauth:
  enabled: true
  dynamicStorage: true

ldap:
  enabled: true
  type: opendj
  extraHosts: [
    host: opendj,
    port: 3434
  ] #array of k,v e.g host: host1, port: port1

shared-shib:
  enabled: true
  dynamicStorage: true

oxtrust:
  enabled: true
  dynamicStorage: true

oxpassport:
  enabled: true
  dynamicStorage: true
  
global:
  namespace: default
  gluuOxauthBackend: oxauth:8080
  gluuLdapBackend: opendj:1636
  serviceName: opendj
  nginxIp: 192.168.99.100
  oxAuthServiceName: oxauth
  oxTrustSeriveName: oxtrust
  domain: demoexample.gluu.org
  gluuLdapUrl: opendj:1636
  gluuMaxRamFraction: 1
  configAdapterName: kubernetes
  configSecretAdapter: kubernetes
  gluuConfigK8sNamespace: default
  gluuConfigK8sConfigmap: gluu
  gluuConfigK8sUseKubeConfig: false
  gluuSecretK8sNamespace: default
  gluuSecretK8sConfigmap: gluu
  gluuSecretK8sUseKubeConfig: false
  gluuSecretAdapter: kubernetes
  provisioner: k8s.io/minikube-hostpath
