apiVersion: v1
kind: Service
metadata:
  name: {{ template "gluu.fullname" . }}
  labels:
{{ include "gluu.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.port }}
    name: {{ template "oxtrust.fullname" . }}
  selector:
{{ include "gluu.labels" . | indent 4 }}
  clusterIP: {{ .Values.clusterIp }}
    