apiVersion: v1
kind: Service
metadata:
  name: {{ template "gluu.fullname" . }}-opendj-service
  labels:
    app: {{ template "gluu.fullname" . }}-opendj
spec:
  ports:
    {{- range $key, $value := .Values.ports }}
    - port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      type: TCP
      name: {{ $key }}
    {{- end }}
  clusterIP: None
  selector:
    app: {{ template "gluu.fullname" . }}
