apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gluu.fullname" . }}-repl-ss
spec:
  serviceName: {{ template "gluu.fullname" . }}-opendj-service
  replicas: {{ .Values.statefulSetReplicas }}
  selector:
    matchLabels:
      app: {{ template "gluu.fullname" . }}-opendj
  template:
    metadata:
      labels:
        app: {{ template "gluu.fullname" . }}-opendj
  spec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - {{ template "gluu.fullname" . }}-opendj
    volumes:
      - name: opendj-repl-ss-volume
        persistentVolumeClaim:
          claimName: {{ template "gluu.fullname" . }}-repl-pvc
    containers:
    - name: {{ template "gluu.fullname" . }}-repl-container
      imagePullPolicy: {{ .Values.imagePullPolicy }}
      image: {{ .Values.image }}
      envFrom:
      - configMapRef:
        name: {{ template "gluu.fullname" . }}-repl-cm
      ports:
        {{- range $key, $value := .Values.ports}}
        - containerPort: {{ $value.targetPort }}
          name: {{ $key }}
        {{- end }}
      volumeMounts:
        {{- range $key, $value := .Values.volumeReplMounts }}
        - mountPath: {{ $value.mountPath }}
          name: {{ $value.name }}
          subPath: {{ $key }}
        {{- end }}
      readinessProbe:
        tcpSocket: 
          port: {{ .Values.readinessProbe.tcpSocket.port }}
        initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
        periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
      livenessProbe:
        tcpSocket:
          port: {{ .Values.livenessProbe.tcpSocket.port }}
        initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
