apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gluu.fullname" . }}-repl-ss
spec:
  serviceName: {{ template "gluu.fullname" . }}-opendj-service
  replicas: {{ .Values.statefulSetReplicas }}
  selector:
    matchLabels:
      app: {{ template "gluu.fullname" . }}-opendj-repl
  template:
    metadata:
      labels:
        app: {{ template "gluu.fullname" . }}-opendj-repl
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ template "gluu.fullname" . }}-opendj-repl
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ template "gluu.fullname" . }}-repl-container
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        image: {{ .Values.image }}
        envFrom:
        - configMapRef:
            name: {{ template "gluu.fullname" . }}-repl-cm
        ports:
          {{- range $key, $value := .Values.ports}}
          - containerPort: {{ $value.targetPort }}
            name: {{ $key }}
          {{- end }}
        volumeMounts:
          {{- range $key, $value := .Values.volumeReplMounts }}
          - mountPath: {{ $value.mountPath }}
            name: {{ $value.name }}
            subPath: {{ $key }}
          {{- end }}
        readinessProbe:
          tcpSocket: 
            port: {{ .Values.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
  volumeClaimTemplates:
  - metadata:
      name: opendj-repl-ss-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ template "gluu.fullname" . }}-repl-sc
      resources:
        requests:
          storage: {{ .Values.storage }}
