apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gluu.fullname" . }}
  labels:
  {{ include "gluu.labels" . | indent 2 }}
spec:
  serviceName: {{ template "gluu.fullname" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{ include "gluu.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "gluu.labels" . | indent 8 }}
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - {{ .Values.global.serviceName }}
      #       topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: opendj-init-volume
          persistentVolumeClaim:
            claimName: {{ template "gluu.fullname" . }}
      containers:
      - name: {{ template "gluu.fullname" . }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        image: {{ .Values.image }}
        envFrom:
        - configMapRef:
            name: {{ template "gluu.fullname" . }}
        ports:
        {{- range $key, $value := .Values.ports }}
          - containerPort: {{ $value.targetPort }}
            name: {{ $key }}
        {{- end }}
        volumeMounts:
        {{- range $key, $value := .Values.volumeInitMounts }}
          - mountPath: {{ $value.mountPath }}
            name: {{ $value.name }}
            subPath: {{ $key }}
        {{- end }}
        readinessProbe:
          tcpSocket: 
            port: {{ .Values.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
  