apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gluu.fullname" . }}-init-ss
spec:
  selector:
    matchLabels:
      app: {{ template "gluu.fullname" . }}-service # has to match .spec.template.metadata.labels
  serviceName: {{ template "gluu.fullname" . }}-service
  replicas: {{ .Values.statefulSetReplicas }} # by default is 1
  template:
    metadata:
      labels:
        app: {{ template "gluu.fullname" . }}-service # has to match .spec.selector.matchLabels
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - {{ template "gluu.fullname" . }}-service
      #       topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: opendj-init-volume
          persistentVolumeClaim:
            claimName: {{ template "gluu.fullname" . }}-config-pvc
      containers:
      - name: {{ template "gluu.fullname" . }}-init-container
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        image: {{ .Values.image }}
        envFrom:
        - configMapRef:
            name: {{ template "gluu.fullname" . }}-init-cm
        ports:
        {{- range $key, $value := .Values.ports }}
          - containerPort: {{ $value.targetPort }}
            name: {{ $key }}
        {{- end }}
        volumeMounts:
        {{- range $key, $value := .Values.volumeInitMounts }}
          - mountPath: {{ $value.mountPath }}
            name: {{ $value.name }}
            subPath: {{ $key }}
        {{- end }}
        readinessProbe:
          tcpSocket: 
            port: {{ .Values.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
  