apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gluu.fullname" . }}-opendj-init
spec:
  selector:
    matchLabels:
      app: {{ template "gluu.fullname" . }}-opendj # has to match .spec.template.metadata.labels
  serviceName: {{ template "gluu.fullname" . }}-opendj-service
  replicas: {{ .Values.statefulSetReplicas }} # by default is 1
  template:
    metadata:
      labels:
        app: {{ template "gluu.fullname" . }}-opendj # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ template "gluu.fullname" . }}-init-container
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        image: {{ .Values.image }}
        envFrom:
        - configMapRef:
            name: {{ template "gluu.fullname" . }}-init-cm
        ports:
          {{- range $key, $value := .Values.ports }}
          - containerPort: {{ $value.targetPort }}
            name: {{ $key }}
          {{- end }}
        volumeMounts:
        {{- range $key, $value := .Values.volumeInitMounts }}
        - name: {{ $value.name }}
          mountPath: {{ $value.mountPath }}
        {{- end }}
        readinessProbe:
          tcpSocket: 
            port: {{ .Values.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
  volumeClaimTemplates:
  - metadata:
      name: opendj-init-ss-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ template "gluu.fullname" . }}-opendj-init-sc
      resources:
        requests:
          storage: 1Gi