apiVersion: v1
kind: Service
metadata:
  name: {{ template "gluu.fullname" . }}
  labels:
{{ include "gluu.labels" . | indent 4 }}
spec:
  ports:
    {{- range $key, $value := .Values.ports }}
    - port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      type: TCP
      name: {{ $key }}
    {{- end }}
  clusterIP: None
  selector:
{{ include "gluu.labels" . | indent 4 }}
