kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gluu.fullname" . }}
spec:
  storageClassName: {{ template "gluu.fullname" . }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
