apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gluu.fullname" . }}-init-cm
data:
  GLUU_CONFIG_ADAPTER: {{ .Values.gluuConfigAdapter | quote }}
  hostname: {{ .Values.hostname | quote }}
  GLUU_SECRET_ADAPTER: {{ .Values.gluuSecretAdapter | quote }}
  GLUU_LDAP_INIT: {{ .Values.gluuLdapInit | quote }}
  GLUU_LDAP_INIT_HOST: {{ template "gluu.fullname" . }}-service
  GLUU_LDAP_INIT_PORT: {{ .Values.gluuLdapInitPort | quote }}
  GLUU_OXTRUST_CONFIG_GENERATION: {{ .Values.gluuOxtrustConfigGeneration | quote }}
  GLUU_CACHE_TYPE: {{ .Values.gluuCacheType | quote }}
  {{- if .Values.gluuRedisEnabled }}
  GLUU_CACHE_TYPE: {{ .Values.gluuRedisCacheType | quote }}
  GLUU_REDIS_URL: {{ .Values.gluuRedisUrl | quote }}
  GLUU_REDIS_TYPE: {{ .Values.gluuRedisType | quote }}
  {{- end }}
  # must the same as the opendj service name
  GLUU_CERT_ALT_NAME: {{ template "gluu.fullname" . }}-service
  