    
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gluu.fullname" . }}-config-volume-claim
spec:
  storageClassName: ""
  volumeName: {{ template "gluu.fullname" . }}-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
  selector:
    matchLabels:
      config-init: {{ template "gluu.fullname" . }}-config
