apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template }}-tiller
  namespace: {{ .Values.namespace }}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{  }}-gluu-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""] # "" refers to the core API group
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{  }}-gluu-role
subjects:
  - kind: ServiceAccount
    name: {{ template }}-tiller
