apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ template "gluu.fullname" . }}-config-cm
  namespace: {{ .Values.global.namespace }}
data:
  ADMIN_PW:  {{ .Values.adminPass }}
  EMAIL: {{ .Values.email }}
  DOMAIN: {{ .Values.domain }}
  ORG_NAME: {{ .Values.orgName }}
  COUNTRY_CODE: {{ .Values.countryCode }}
  STATE: {{ .Values.state }}
  CITY: {{ .Values.city }}
  LDAP_TYPE: {{ .Values.ldapType }}
<<<<<<< HEAD
  GLUU_CONFIG_ADAPTER: {{ .Values.configAdapterName }}
  GLUU_SECRET_ADAPTER: {{ .Values.configSecretAdapter }}
=======
  
>>>>>>> c5d14f8... fix(config job) identation error
