apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "gluu.fullname" . }}-config-init
spec:
  template:
    metadata:
      labels: 
        app: {{ template "gluu.fullname" . }}-config-init
    spec:
      restartPolicy: Never
      volumes:
        - name: {{ template "gluu.fullname" . }}-config
          persistentVolumeClaim: 
            claimName: {{ template "gluu.fullname" . }}-config-volume-claim
      containers:
        - name: {{ template "gluu.fullname" . }}-config-init
          image: gluufederation/config-init:3.1.6_02
          volumeMounts:
            - mountPath: /opt/config-init/db/
              name: {{ template "gluu.fullname" . }}-config
          env:
            - name: GLUU_CONFIG_ADAPTER
              value: kubernetes
            - name: GLUU_SECRET_ADAPTER
              value: kubernetes
            - name: ADMIN_PW
              value: "secret"
            - name: EMAIL
              value: "support@gluu.local"
            - name: DOMAIN
              value: "kube.gluu.local"
            - name: ORG_NAME
              value: "Gluu, Inc"
            - name: COUNTRY_CODE
              value: "US"
            - name: STATE
              value: "TX"
            - name: CITY
              value: "Austin"
            - name: LDAP_TYPE
              value: "opendj"
