apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gluu.fullname" . }}-gen-json-file
  namespace: {{ .Values.global.namespace }}
data:
  generate.json: |-
    {
      "hostname": {{ .Values.global.domain | quote }},
      "country_code": {{ .Values.countryCode | quote }},
      "state": {{ .Values.state | quote }},
      "city": {{ .Values.city | quote }},
      "admin_pw": {{ .Values.adminPass | quote }},
      "email": {{ .Values.email | quote }},
      "org_name": {{ .Values.orgName | quote }}
    }
