apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "gluu.fullname" . }}
spec:
  parallelism: {{ .Values.parallelism }}
  completions: {{ .Values.completions }}
  template:
    metadata:
      name: {{ template "gluu.name" . }}-job
      labels:
        app: {{ template "gluu.name" . }}-load
    spec:
      volumes:
        - name: {{ template "gluu.name" . }}-config
          persistentVolumeClaim:
            claimName: {{ template "gluu.fullname" . }}-config-pvc
      containers:
      - name: {{ template "gluu.name" . }}-load
        image: gluufederation/config-init:4.0.0_dev
        volumeMounts:
          - mountPath: /opt/config-init/db/
            name: {{ template "gluu.name" . }}-config
        envFrom:
        - configMapRef:
            name: {{ template "gluu.fullname" . }}-config-cm
        args: [ "dump" ]
      restartPolicy: Never
          