apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "gluu.fullname" . }}
spec:
  template:
    metadata:
      name: {{ template "gluu.name" . }}-job
      labels:
        app: {{ template "gluu.name" . }}-load
    spec:
      volumes:
        - name: {{ template "gluu.name" . }}-config
          persistentVolumeClaim:
            claimName: {{ template "gluu.fullname" . }}-config-pvc
        - name: {{ template "gluu.fullname" . }}-mount-gen-file
          configMap:
            name: {{ template "gluu.fullname" . }}-gen-json-file
        - name: {{ template "gluu.fullname" . }}-tls-script
          configMap:
            name: {{ template "gluu.fullname" . }}-tls-script
      containers:
      - name: {{ template "gluu.name" . }}-load
        image: gluufederation/config-init:4.0.0_dev
        volumeMounts:
          - mountPath: /opt/config-init/db/
            name: {{ template "gluu.name" . }}-config
          - mountPath: /opt/config-init/db/generate.json
            name: {{ template "gluu.fullname" . }}-mount-gen-file
            subPath: generate.json
          - mountPath: /opt/config-init/db/tls_generator.py
            name: {{ template "gluu.fullname" . }}-tls-script
        envFrom:
        - configMapRef:
            name: {{ template "gluu.fullname" . }}-config-cm
        command: ["/bin/sh", "-c"]
        args: ["tini -g -- /app/scripts/entrypoint.sh load && python /opt/config-init/db/tls_generator.py"]
      restartPolicy: Never
          