apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "gluu.fullname" . }}-load
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      labels: 
        app: {{ template "gluu.fullname" . }}-load
    spec: 
      restartPolicy: Never
      volumes:
        - name: {{ template "gluu.fullname" . }}-config
          persistentVolumeClaim:
            claimName: {{ template "gluu.fullname" . }}-config-volume-claim
      containers:
        - name: {{ template "gluu.fullname" . }}-load
          image: gluufederation/config-init:3.1.6_03
          volumeMounts:
            - mountPath: /opt/config-init/db
              name: {{ template "gluu.fullname" . }}-config
              subPath: db
          envFrom:
          - configMapRef:
              name: {{ template "gluu.fullname" . }}-load-cm
          args: [ "load" ]


