apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ template "gluu.fullname" . }}-config-cm
  namespace: {{ .Values.global.namespace }}
data:
  GLUU_CONFIG_ADAPTER: {{ .Values.global.configAdapterName }}
  GLUU_SECRET_ADAPTER: {{ .Values.global.configSecretAdapter }}
