apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "gluu.fullname" . }}
spec:
  template:
    metadata:
      name: {{ template "gluu.name" . }}-job
      labels:
        app: {{ template "gluu.name" . }}-load
    spec:
      volumes:
        - name: {{ template "gluu.name" . }}-config
          persistentVolumeClaim:
            claimName: {{ template "gluu.fullname" . }}-config-pvc
        - name: {{ template "gluu.fullname" . }}-mount-gen-file
          configMap:
            name: {{ template "gluu.fullname" . }}-gen-json-file
      containers:
      - name: {{ template "gluu.name" . }}-load
        image: gluufederation/config-init:4.0.0_dev
        volumeMounts:
          - mountPath: /opt/config-init/db/
            name: {{ template "gluu.name" . }}-config
          - mountPath: /opt/config-init/db/generate.json
            name: {{ template "gluu.fullname" . }}-mount-gen-file
            subPath: generate.json
        envFrom:
        - configMapRef:
            name: {{ template "gluu.fullname" . }}-config-cm
        args: [ "load" ]
      restartPolicy: Never
          