apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gluu.fullname" . }}
  labels:
{{ include "gluu.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "gluu.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "gluu.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ template "gluu.fullname" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: gluufederation/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: {{ .Values.requests.memory }}
          # limits:
          #   memory: {{ .Values.limits.memory }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ template "gluu.fullname" . }}
        volumeMounts:
        {{- range $key, $value := .Values.volumeMounts }}
          - mountPath: {{ $value.mountPath }}
            name: {{ $value.name }}
            subPath: {{ $key }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: {{ .Values.ports.containerPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        readinessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: {{ .Values.ports.containerPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
      hostAliases:
      - ip: {{ .Values.global.nginxIp }}
        hostnames:
        - {{ .Values.global.domain }}
      volumes:
      - name: oxauth-volume
        persistentVolumeClaim:
          claimName: {{ template "gluu.fullname" . }}-storage-pvc
