apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "radius.fullname" . }}
data:
  LB_ADDR: {{ .Values.configMap.lbAddr }}
  GLUU_CONFIG_ADAPTER: {{ .Values.global.configAdapterName | quoute }}
  GLUU_SECRET_ADAPTER: {{ .Values.global.configSecretAdapter | quote }}
  DOMAIN: {{ .Values.global.domain }}
  GLUU_MAX_RAM_FRACTION: {{ .Values.global.gluuMaxRamFraction }}
  GLUU_OXAUTH_BACKEND: {{ .Values.oxauthBackendUrl | quote }}
  GLUU_PERSISTENCE_TYPE: {{ .Values.configMap.gluuPersistenceType | quote }}
  # options: default/user/site/cache/statistic; used only if GLUU_PERSISTENCE_TYPE is hybrid
  {{- if eq .Values.configmap.gluuPersistenceType "hybrid" }}
  GLUU_PERSISTENCE_LDAP_MAPPING: default
  {{- end }}
  {{- if eq or .Values.configMap.gluuPersistenceType "ldap" ( eq .Values.configMap.gluuPersistenceType "hybrid")  }}
  # used only if GLUU_PERSISTENCE_TYPE is ldap or hybrid
  GLUU_LDAP_URL: {{ .Values.global.gluuLdapUrl | quote }}
  {{- else if eq or .Values.configMap "couchbase" ( eq .Values.configMap.gluuPersistenceType "hybrid" ) }}
  # used only if GLUU_PERSISTENCE_TYPE is couchbase or hybrid
  GLUU_COUCHBASE_URL: {{ .Values.configMap.gluuCouchBaseUrl }}
  {{- end }}