# Default values for oxtrust.
# Declare variables to be passed into your templates.

replicaCount: 1
gluuMaxRamFraction: 1

dynamicStorage: true

image:
  repository: nginx
  tag: 4.0.0_dev
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

# PVC storage
volumeClaim:
  storage: 10M

#resources: 
limits:
  memory: 128Mi
requests:
  memory: 300Mi

#containerPOrt ot connect the container with
containerPort: 8080

gluuOxauthBackend: oxauth:8080

#service values
#port for which to open in oxtrust ss
port: 8080
clusterIp: None

#VolumeMounts
volumeMounts:
  logs:
    mountPath: /opt/gluu/jetty/identity/logs
    name: oxtrust
  ext:
    mountPath: /opt/gluu/jetty/identity/lib/ext
    name: oxtrust
  static:
    mountPath: /opt/gluu/jetty/identity/custom/static
    name: oxtrust
  pages:
    mountPath: /opt/gluu/jetty/identity/custom/pages
    name: oxtrust
    