# Required environment variables for generating Gluu server initial config
#values for environment variables
orgName: Gluu
adminPass: P@ssw0rd
email: support@gluu.com
domain: demoexample.gluu.org
countryCode: US
state: TE
city: SLC
ldapType: opendj
configAdapterName: kubernetes
configSecretAdapter: kubernetes

# VolumeClaim values
volumeClaim:
  storage: 1Gi
