#values for environment variables

orgName: Gluu
adminPass: password
email: support@gluu.com
domain: localhost
country: US
state: TE
city: SLC
ldapType: opendj

# values for storage class
storageclass:
  encrypted: "true"
  reclaimPolicy: Retain

# VolumeClaim values
volumeclaim:
  storage: 1Gi
