#values for environment variables

orgName: k8s
# email address of the administrator usually. Used for certificate creation
email: k8s@email.com
# adminPass is administrator password for oxTrust and LDAP
adminPass: password
# domain name where the Gluu Server resides
domain: localhost
# organisation location details
countryCode: US
state: UT
city: SLC
# ldapType only OpenDJ is supported
ldapType: opendj
