#values for environment variables

orgName: Gluu
adminPass: password
email: k8s@email.com
domain: localhost
country: US
state: TE
city: SLC
ldapType: opendj
configAdapterName: kubernetes
confiSecretgAdapter: kubernetes
