# opendj Environament Variables
# common ConfigMap values
gluuConfigAdapter: kubernetes
gluuSecretAdapter: kubernetes
gluuLdapInit: true
gluuLdapInitHost: opendj
gluuLdapInitPort: 1636
gluuOxtrustConfigGeneration: true
gluuCacheType: NATIVE_PERSISTENCE
gluuCertAltName: opendj
# gluuRedisEnabled will determin if GLUU_REDIS_URL and GLUU_REDIS_TYPE if they will be used.
gluuRedisEnabled: false
gluuRedisCacheType: REDIS
gluuRedisUrl: redis:6379
gluuRedisType: STANDALONE
#repl diferent env vars
gluuLdapInitRepl: false
gluuOxtrustConfigGenerationRepl: false

# StatefulSet 
# values declaration
statefulSetReplicas: 1
imagePullPolicy: Always
image: gluufederation/opendj:3.1.6_02

# VolumeClaim values
volumeclaim:
  storage: 20Gi

#container specific values declared here
readinessProbe:
  tcpSocket:
    port: 1636
  initialDelaySeconds: 25
  periodSeconds: 25
livenessProbe:
  tcpSocket:
    port: 1636
  initialDelaySeconds: 30
  periodSeconds: 30

#servicePorts values used in StatefulSet container
ports:
  ldaps:
    port: 1636
    targetPort: 1636
  ldap:
    port: 1389
    targetPort: 1389
  replication:
    port: 8989
    targetPort: 8989
  admin:
    port: 4444
    targetPort: 4444
# VolumeMounts for StatefulSet
# opendj-init vm
volumeInitMounts:
  config:
    mountPath: /opt/opendj/config
    name: opendj-init-ss-volume
  ldif: 
    mountPath: /opt/opendj/ldif
    name: opendj-init-ss-volume
  logs: 
    mountPath: /opt/opendj/logs
    name: opendj-init-ss-volume
  db: 
    mountPath: /opt/opendj/db
    name: opendj-init-ss-volume
  flag: 
    mountPath: /flag
    name: opendj-init-ss-volume

#opedj-repl vm
volumeReplMounts:
  config:
    mountPath: /opt/opendj/config
    name: opendj-repl-ss-volume
  ldif: 
    mountPath: /opt/opendj/ldif
    name: opendj-repl-ss-volume
  logs: 
    mountPath: /opt/opendj/logs
    name: opendj-repl-ss-volume
  db: 
    mountPath: /opt/opendj/db
    name: opendj-repl-ss-volume
  flag: 
    mountPath: /flag
    name: opendj-repl-ss-volume
